language: haskell
before_install:
  - git clone https://github.com/galoisinc/ivory
  - export IVORY_REPO=$PWD/ivory
  - git clone https://github.com/galoisinc/tower
  - export TOWER_REPO=$PWD/tower
install:
  - cabal install cabal-install
  - cabal install alex happy
script:
  - echo $PATH
  - make $ENV_TEST_TARGET
ghc:
  - 7.8
env:
  - ENV_TEST_TARGET=ivory-freertos-bindings
  - ENV_TEST_TARGET=ivory-bsp-stm32
  - ENV_TEST_TARGET=tower-freertos-stm32
  - ENV_TEST_TARGET=tower-freertos-stm32-tests
  - ENV_TEST_TARGET=ivory-bsp-tests
