language: haskell
before_install:
  - git clone https://github.com/galoisinc/ivory
  - export IVORY_REPO=$PWD/ivory
  - git clone https://github.com/galoisinc/tower
  - export TOWER_REPO=$PWD/tower
install:
  - cabal install cabal-install
  - cabal install alex happy
script:
  - make create-sandbox
  - make
  - make test
ghc:
  - 7.8
